import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { ArrowUpCircle, Copy, KeyRound, RefreshCw, X } from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';
import { apiGet, apiPost } from '../../api/client';
import { HyperTable, type HyperTableColumn } from '../../components/table';

type MigrationSession={id:string;sourceInstanceId:string;targetInstanceId:string;protocolVersion:string;state:string;frozen:boolean;expiresAt:string;createdAt:string;updatedAt:string;lastErrorCode?:string;lastErrorMessage?:string};
type Authorization={id:string;token:string;expiresAt:string;protocolVersion:string};

export default function CommunityMigrationAuthorizationsPage({toast}:{toast:(message:string)=>void}){
 const[items,setItems]=useState<MigrationSession[]>([]);const[loading,setLoading]=useState(true);const[creating,setCreating]=useState(false);const[authorization,setAuthorization]=useState<Authorization|null>(null);const[selected,setSelected]=useState<MigrationSession|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const response=await apiGet<{items:MigrationSession[]}>('/api/v1/community-migrations');setItems(response.items||[])}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const create=async()=>{setCreating(true);try{const result=await apiPost<Authorization>('/api/v1/community-migrations/authorizations',{});setAuthorization(result);toast('One-time migration authorization created')}finally{setCreating(false)}};
 const copy=async()=>{if(!authorization)return;await navigator.clipboard.writeText(authorization.token);toast('Migration authorization copied')};
 const columns=useMemo<HyperTableColumn<MigrationSession>[]>(()=>[
  {accessorKey:'state',header:'Status',size:150,cell:({row}:any)=><span className={`hbdr-status-pill ${row.original.state==='committed'?'success':row.original.state.includes('failed')?'danger':'info'}`}>{row.original.state}</span>,meta:{kind:'status'}},
  {accessorKey:'targetInstanceId',header:'Enterprise Instance',size:250,cell:({row}:any)=><span>{row.original.targetInstanceId||'-'}</span>,meta:{kind:'code'}},
  {accessorKey:'protocolVersion',header:'Protocol',size:220,meta:{kind:'secondary'}},
  {accessorKey:'createdAt',header:'Created',size:180,cell:({row}:any)=>new Date(row.original.createdAt).toLocaleString(),meta:{kind:'secondary'}},
 ],[]);
 return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-5"><div className="hbdr-page-hero"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 text-blue-600"><ArrowUpCircle size={18}/></div><div><h3 className="text-sm font-black text-slate-900">Upgrade to Enterprise</h3><p className="mt-1 text-[11px] text-slate-400">Authorize an Enterprise control plane to import this Community instance.</p></div></div></div><section className="hbdr-dr-table-card"><div className="hbdr-dr-table-head"><div className="hbdr-dr-toolbar"><div className="hbdr-dr-action-group"><button className="hbdr-dr-action-primary" disabled={creating||items.some(item=>!['committed','rolled-back','failed','revoked','expired'].includes(item.state))} onClick={()=>void create()}><KeyRound size={15}/>New Authorization</button></div><button className="hbdr-dr-action-secondary" disabled={loading} onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></div></div><HyperTable variant="page" density="comfortable" columns={columns} data={items} getRowId={row=>row.id} onRowClick={row=>setSelected(row)} emptyMessage={loading?'Loading migrations…':'No migration has been authorized.'} resetPageOnDataChange/></section><AnimatePresence>{authorization&&<Drawer title="Migration Authorization" subtitle="This token is shown once and expires in 30 minutes." close={()=>setAuthorization(null)}><div className="hbdr-advanced-filter-box space-y-3"><p className="text-xs text-slate-500">Paste the source URL and token into Settings → Community Migration on the Enterprise platform.</p><div className="rounded-lg border border-slate-200 bg-slate-950 p-3 font-mono text-xs leading-5 text-slate-100 break-all">{authorization.token}</div><p className="text-[11px] text-slate-400">Expires {new Date(authorization.expiresAt).toLocaleString()}</p><button className="hbdr-dr-action-primary" onClick={()=>void copy()}><Copy size={14}/>Copy Token</button></div></Drawer>}{selected&&<Drawer title="Migration Details" subtitle={selected.id} close={()=>setSelected(null)}><dl className="hbdr-resource-detail-section"><div><dt>Status</dt><dd>{selected.state}</dd></div><div><dt>Target instance</dt><dd>{selected.targetInstanceId||'-'}</dd></div><div><dt>Source frozen</dt><dd>{selected.frozen?'Yes':'No'}</dd></div><div><dt>Updated</dt><dd>{new Date(selected.updatedAt).toLocaleString()}</dd></div>{selected.lastErrorMessage&&<div><dt>Last error</dt><dd>{selected.lastErrorMessage}</dd></div>}</dl></Drawer>}</AnimatePresence></motion.div>
}
function Drawer({title,subtitle,close,children}:{title:string;subtitle:string;close:()=>void;children:ReactNode}){return <><motion.div className="hbdr-filter-drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}/><motion.aside className="hbdr-filter-drawer" initial={{x:34,opacity:0}} animate={{x:0,opacity:1}} exit={{x:34,opacity:0}} role="dialog" aria-modal="true"><div className="hbdr-filter-drawer-head"><div><strong>{title}</strong><span>{subtitle}</span></div><button onClick={close}><X size={18}/></button></div><div className="hbdr-filter-drawer-body">{children}</div></motion.aside></>}
