import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { ChevronDown, KeyRound, User, X } from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';
import { apiGet, apiPatch, apiPost } from '../../api/client';
import type { ApiLoginResponse } from '../../auth/types';
import { EditField } from '../../components/edit-field';
import { PasswordValidation } from '../../components/password-validation';
import { HyperTable, type HyperTableColumn } from '../../components/table';

type CommunityUser = { id:string; email:string; displayName?:string; status:string; authProvider:string; role:string; recoveryEmail?:string };

export default function CommunityUserManagementPage({ toast }: { currentUser:ApiLoginResponse['user']; toast:(message:string)=>void }) {
  const [items,setItems]=useState<CommunityUser[]>([]); const [selected,setSelected]=useState(false); const [more,setMore]=useState(false);
  const [panel,setPanel]=useState<'profile'|'recovery'|'password'|null>(null); const [displayName,setDisplayName]=useState(''); const [recoveryEmail,setRecoveryEmail]=useState('');
  const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>setItems((await apiGet<{items:CommunityUser[]}>('/api/v1/users')).items||[]),[]); useEffect(()=>{void load()},[load]); const admin=items[0];
  const columns:HyperTableColumn<CommunityUser>[]=[
    {id:'select',header:'',size:46,enableSorting:false,cell:()=> <input type="checkbox" aria-label="Select admin" checked={selected} onChange={()=>setSelected(v=>!v)}/>},
    {id:'user',header:'User',accessorFn:r=>r.email,size:220,cell:i=><div><span>{i.row.original.displayName||'Administrator'}</span><p className="text-[11px] font-normal text-slate-400">{i.row.original.email}</p></div>,meta:{kind:'primary'}},
    {id:'role',header:'Role',accessorFn:r=>r.role,size:200,cell:()=> <span>System Administrator</span>,meta:{kind:'secondary'}},
    {id:'recovery',header:'Recovery Email',accessorFn:r=>r.recoveryEmail||'',size:240,cell:i=>i.row.original.recoveryEmail||'Not configured',meta:{kind:'secondary'}},
    {id:'status',header:'Status',accessorFn:r=>r.status,size:110,meta:{kind:'status'}},{id:'signIn',header:'Sign-in',accessorFn:r=>r.authProvider,size:110,meta:{kind:'secondary'}},
  ];
  const saveProfile=async()=>{if(!admin)return;setBusy(true);try{await apiPatch(`/api/v1/users/${admin.id}`,{displayName});setPanel(null);await load();toast('Administrator profile updated.')}finally{setBusy(false)}};
  const saveRecovery=async()=>{if(!admin)return;setBusy(true);try{await apiPatch(`/api/v1/users/${admin.id}/recovery-email`,{email:recoveryEmail});setPanel(null);await load();toast('Recovery email verified and saved.')}finally{setBusy(false)}};
  const resetPassword=async()=>{if(!admin)return;setBusy(true);try{await apiPost(`/api/v1/users/${admin.id}/password`,{password});setPanel(null);toast('Administrator password reset. Sign in again with the new password.')}finally{setBusy(false)}};
  const open=(next:'profile'|'recovery'|'password')=>{if(!admin)return;setDisplayName(admin.displayName||'');setRecoveryEmail(admin.recoveryEmail||'');setPassword('');setConfirm('');setPanel(next);setMore(false)};
  return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-5">
    <div className="hbdr-page-hero"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 text-blue-600"><User size={18}/></div><div><h3 className="text-sm font-black text-slate-900">User Management</h3><p className="mt-1 text-[11px] text-slate-400">Community uses one protected built-in administrator.</p></div></div></div>
    <section className="hbdr-dr-table-card"><div className="hbdr-dr-table-head"><div className="hbdr-dr-toolbar"><div className="hbdr-dr-action-group"><div className="relative"><button className="hbdr-dr-more" disabled={!selected||!admin} onClick={()=>setMore(v=>!v)}>More <ChevronDown size={15}/></button><AnimatePresence>{more&&<><div className="fixed inset-0 z-30" onClick={()=>setMore(false)}/><motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}} className="absolute left-0 top-11 z-40 w-52 rounded-xl border bg-white py-1 shadow-xl"><MenuButton label="Edit Profile" run={()=>open('profile')}/><MenuButton label="Configure Recovery Email" run={()=>open('recovery')}/><MenuButton label="Reset Password" icon={<KeyRound size={14}/>} run={()=>open('password')}/></motion.div></>}</AnimatePresence></div></div></div></div><HyperTable variant="page" density="comfortable" columns={columns} data={items} getRowId={r=>r.id} onRowClick={()=>setSelected(v=>!v)} getRowClassName={()=>selected?'hbdr-dr-row-selected':''} selectedCount={selected?1:0} emptyMessage="The built-in administrator could not be loaded."/></section>
    <AnimatePresence>{panel==='profile'&&<Drawer title="Edit Administrator" subtitle="The account, role, and active status are protected." close={()=>!busy&&setPanel(null)}><EditField label="Display Name" value={displayName} onChange={setDisplayName}/><Actions disabled={busy} label="Save Changes" run={()=>void saveProfile()} close={()=>setPanel(null)}/></Drawer>}{panel==='recovery'&&<Drawer title="Configure Recovery Email" subtitle="Password reset instructions are sent to this verified address." close={()=>!busy&&setPanel(null)}><EditField label="Recovery Email" value={recoveryEmail} onChange={setRecoveryEmail}/><Actions disabled={busy||!recoveryEmail.includes('@')} label="Save Recovery Email" run={()=>void saveRecovery()} close={()=>setPanel(null)}/></Drawer>}{panel==='password'&&<Drawer title="Reset Password" subtitle="This invalidates existing administrator sessions." close={()=>!busy&&setPanel(null)}><div className="space-y-4"><EditField label="New Password" type="password" value={password} onChange={setPassword}/><EditField label="Confirm Password" type="password" value={confirm} onChange={setConfirm}/><PasswordValidation password={password} confirmation={confirm}/></div><Actions disabled={busy||password.length<8||password!==confirm} label="Reset Password" run={()=>void resetPassword()} close={()=>setPanel(null)}/></Drawer>}</AnimatePresence>
  </motion.div>;
}
function MenuButton({label,icon,run}:{label:string;icon?:ReactNode;run:()=>void}){return <button className="flex w-full items-center gap-2 px-4 py-2.5 text-left text-xs font-bold text-slate-600 hover:bg-slate-50" onClick={run}>{icon}{label}</button>}
function Drawer({title,subtitle,close,children}:{title:string;subtitle:string;close:()=>void;children:ReactNode}){return <><motion.div className="hbdr-filter-drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}/><motion.aside className="hbdr-filter-drawer" initial={{x:34,opacity:0}} animate={{x:0,opacity:1}} exit={{x:34,opacity:0}} role="dialog" aria-modal="true" aria-label={title}><div className="hbdr-filter-drawer-head"><div><strong>{title}</strong><span>{subtitle}</span></div><button onClick={close} aria-label={`Close ${title}`}><X size={18}/></button></div><div className="hbdr-filter-drawer-body">{children}</div></motion.aside></>}
function Actions({disabled,label,run,close}:{disabled:boolean;label:string;run:()=>void;close:()=>void}){return <div className="hbdr-filter-drawer-actions"><button disabled={disabled} onClick={run}>{label}</button><button disabled={disabled} onClick={close}>Cancel</button></div>}
