import type { ClusterNode, ClusterStorageClass } from '../clusters/types';

export type ApiCluster = {
  id: string;
  tenantId: string;
  name: string;
  kubeVersion: string;
  status: string;
  connectionStatus: string;
  nodeCount: number;
  nodes?: ClusterNode[];
  storageClasses?: ClusterStorageClass[];
  apiResources?: Array<{
    group?: string;
    version: string;
    resource: string;
    kind: string;
    namespaced: boolean;
  }>;
  namespaceAPIs?: Array<{
    namespace: string;
    group?: string;
    version: string;
    resource: string;
    kind: string;
    count: number;
  }>;
  namespaceCount: number;
  applicationCount: number;
  complianceScore?: number;
  agentVersion: string;
  agentImage?: string;
  agentImageId?: string;
  agentImageDigest?: string;
  latestAgentVersion?: string;
  latestAgentImage?: string;
  latestAgentImageDigest?: string;
  agentUpgradeAvailable?: boolean;
  agentUpgradeStatus?: string;
  agentUpgradeProgress?: number;
  veleroVersion?: string;
  veleroStatus: string;
  veleroImage?: string;
  veleroImageDigest?: string;
  veleroServerReady?: boolean;
  veleroNodeAgentDesired?: number;
  veleroNodeAgentReady?: number;
  veleroNodeAgentImageDigest?: string;
  latestVeleroVersion?: string;
  latestVeleroImage?: string;
  latestVeleroImageDigest?: string;
  veleroUpgradeAvailable?: boolean;
  veleroUpgradeStatus?: string;
  veleroUpgradeProgress?: number;
  role?: 'source' | 'target' | 'both';
  isDefault?: boolean;
  registeredAt?: string;
  lastSeenAt?: string;
};

export type ApiStorageRepo = {
  id: string;
  name: string;
  type: string;
  endpoint?: string;
  bucket?: string;
  region?: string;
  tlsEnabled: boolean;
  status: string;
  updatedAt?: string;
  createdAt?: string;
  lastValidatedAt?: string;
  config?: Record<string, unknown>;
};
