package httpserver

import "strings"

func (r *Router) routes() {
	r.mountPlatformRoutes()
	r.mountAuthRoutes()
	if r.productInfo.Edition == "community" {
		r.handleRoute("GET /api/v1/audit-logs", r.listAuditLogs)
	}
	if r.productInfo.Edition == "community" {
		r.handleRoute("GET /api/v1/diagnostic-logs", r.listDiagnosticLogs)
		r.handleRoute("GET /api/v1/diagnostic-logs/export", r.exportDiagnosticLogs)
		r.handleRoute("GET /api/v1/diagnostic-log-sources", r.diagnosticLogSources)
		r.handleRoute("POST /api/v1/support-bundles", r.createSupportBundle)
		r.handleRoute("GET /api/v1/support-bundles/{name}/download", r.downloadSupportBundle)
		r.handleRoute("DELETE /api/v1/support-bundles/{name}", r.deleteSupportBundle)
	}
	r.handleRoute("POST /api/v1/clusters/{id}/logs/collect", r.collectClusterLogs)
	r.handleRoute("POST /api/v1/clusters/{id}/logs/search", r.searchClusterLogs)
	if r.productInfo.Edition == "community" {
		r.handleRoute("GET /api/v1/users", r.listCommunityUsers)
		r.handleRoute("PATCH /api/v1/users/{id}", r.updateCommunityAdmin)
		r.handleRoute("POST /api/v1/users/{id}/password", r.resetCommunityAdminPassword)
		r.handleRoute("PATCH /api/v1/users/{id}/recovery-email", r.updateCommunityAdminRecoveryEmail)
	}
	r.handleRoute("GET /api/v1/email-settings", r.getEmailSettings)
	r.handleRoute("PUT /api/v1/email-settings", r.updateEmailSettings)
	r.handleRoute("POST /api/v1/email-settings/test", r.testEmailSettings)
	r.handleRoute("GET /api/v1/email-settings/configurations", r.listEmailSettings)
	r.handleRoute("POST /api/v1/email-settings/configurations", r.createEmailSettings)
	r.handleRoute("PUT /api/v1/email-settings/configurations/{id}", r.updateEmailSettingsByID)
	r.handleRoute("DELETE /api/v1/email-settings/configurations/{id}", r.deleteEmailSettings)
	r.handleRoute("POST /api/v1/email-settings/configurations/{id}/default", r.setDefaultEmailSettings)
	r.handleRoute("POST /api/v1/email-settings/configurations/{id}/test", r.testEmailSettingsByID)
	r.handleRoute("GET /api/v1/clusters", r.listClusters)
	r.handleRoute("POST /api/v1/cluster-registrations/cce/kubeconfigs", r.uploadCCEKubeconfig)
	r.handleRoute("POST /api/v1/cluster-registrations/cce/inspections", r.inspectCCEKubeconfig)
	r.handleRoute("POST /api/v1/cluster-registrations/cce/tasks", r.startCCEDirectRegistration)
	r.handleRoute("DELETE /api/v1/cluster-registrations/cce/kubeconfigs/{id}", r.deleteCCEKubeconfig)
	r.handleRoute("POST /api/v1/cluster-registrations/kubeconfigs", r.uploadCCEKubeconfig)
	r.handleRoute("POST /api/v1/cluster-registrations/inspections", r.inspectCCEKubeconfig)
	r.handleRoute("POST /api/v1/cluster-registrations/tasks", r.startCCEDirectRegistration)
	r.handleRoute("DELETE /api/v1/cluster-registrations/kubeconfigs/{id}", r.deleteCCEKubeconfig)
	r.handleRoute("PATCH /api/v1/clusters/{id}", r.updateCluster)
	r.handleRoute("DELETE /api/v1/clusters/{id}", r.deleteCluster)
	r.handleRoute("POST /api/v1/clusters/{id}/default", r.setDefaultCluster)
	r.handleRoute("POST /api/v1/clusters/{id}/force-cleanup", r.forceCleanupCluster)
	r.handleRoute("GET /api/v1/clusters/{id}/unregister/precheck", r.precheckUnregisterCluster)
	r.handleRoute("POST /api/v1/clusters/{id}/unregister", r.unregisterCluster)
	r.handleRoute("POST /api/v1/clusters/{id}/agent/upgrade", r.upgradeClusterAgent)
	r.handleRoute("POST /api/v1/clusters/{id}/velero/upgrade", r.upgradeClusterVelero)
	r.handleRoute("POST /api/v1/clusters/{id}/inventory/request", r.requestClusterInventory)
	r.handleRoute("GET /api/v1/clusters/{id}/inventory/requests/{requestId}", r.getClusterInventoryRequest)
	r.handleRoute("GET /api/v1/applications", r.listApplications)
	r.handleRoute("PATCH /api/v1/applications/{id}", r.updateApplication)
	r.handleRoute("PUT /api/v1/applications/{id}/tags", r.setApplicationTags)
	r.handleRoute("GET /api/v1/tags", r.listTags)
	r.handleRoute("POST /api/v1/tags", r.createTag)
	r.handleRoute("PATCH /api/v1/tags/{id}", r.updateTag)
	r.handleRoute("DELETE /api/v1/tags/{id}", r.deleteTag)
	r.handleRoute("GET /api/v1/storage-repositories", r.listStorageRepositories)
	r.handleRoute("POST /api/v1/storage-repositories", r.createStorageRepository)
	r.handleRoute("PATCH /api/v1/storage-repositories/{id}", r.updateStorageRepository)
	r.handleRoute("DELETE /api/v1/storage-repositories/{id}", r.deleteStorageRepository)
	r.handleRoute("POST /api/v1/storage-repositories/test", r.testStorageRepositoryDraft)
	r.handleRoute("POST /api/v1/storage-repositories/{id}/sync", r.syncStorageRepository)
	r.handleRoute("POST /api/v1/storage-repositories/{id}/test", r.testStorageRepository)
	r.handleRoute("GET /api/v1/policies", r.listPolicies)
	r.handleRoute("POST /api/v1/policies", r.createPolicy)
	r.handleRoute("PATCH /api/v1/policies/{id}", r.updatePolicy)
	r.handleRoute("DELETE /api/v1/policies/{id}", r.deletePolicy)
	r.handleRoute("GET /api/v1/protection-plans", r.listProtectionPlans)
	r.handleRoute("POST /api/v1/protection-plans", r.createProtectionPlan)
	r.handleRoute("POST /api/v1/protection-plans/{id}/activate", r.activateProtectionPlan)
	r.handleRoute("POST /api/v1/protection-plans/{id}/storage/reconfigure", r.reconfigureProtectionPlanStorage)
	r.handleRoute("DELETE /api/v1/protection-plans/{id}", r.deleteProtectionPlan)
	r.handleRoute("GET /api/v1/restore-points", r.listRestorePoints)
	r.handleRoute("GET /api/v1/restore-points/{id}/contents", r.getRestorePointContents)
	r.handleRoute("POST /api/v1/restore-points/delete", r.deleteRestorePoints)
	r.handleRoute("GET /api/v1/tasks", r.listTasks)
	r.handleRoute("GET /api/v1/protection-plans/{id}/latest-sync", r.latestPlanTask("backup"))
	r.handleRoute("GET /api/v1/protection-plans/{id}/latest-recovery", r.latestPlanRecoveryTask)
	r.handleRoute("GET /api/v1/tasks/{id}", r.getTask)
	r.handleRoute("GET /api/v1/tasks/{id}/events", r.listTaskEvents)
	r.handleRoute("POST /api/v1/tasks/{id}/cancel", r.cancelTask)
	r.handleRoute("POST /api/v1/tasks/{id}/retry", r.retryRecoveryTask)
	r.handleRoute("POST /api/v1/tasks/{id}/cleanup-drill", r.cleanupDrillTask)
	r.handleRoute("POST /api/v1/tasks/backup", r.createBackupTask)
	r.handleRoute("POST /api/v1/tasks/restore", r.createRestoreTask)
	r.handleRoute("POST /api/v1/tasks/drill", r.createDrillTask)
	r.handleRoute("POST /api/v1/tasks/takeover", r.createTakeoverTask)
	r.handleRoute("POST /api/v1/agent-tokens", r.createAgentToken)
	r.handleRoute("POST /api/v1/agent-tokens/validate", r.validateAgentToken)
	r.handleRoute("GET /prepare-node.sh", r.prepareNodeScript)
	r.handleRoute("GET /install.sh", r.installScript)
	r.handleRoute("GET /uninstall-agent.sh", r.agentUninstallScript)
	r.handleRoute("GET /disaster-handover.sh", r.disasterHandoverScript)
	r.handleRoute("POST /api/v1/disaster-handovers/validate", r.validateDisasterHandoverToken)
	r.handleRoute("GET "+veleroCRDsPath, r.veleroCRDs)
	// Keep the previous asset URL available while installed agents roll forward.
	r.handleRoute("GET /assets/velero/v1.17.1/crds.yaml", r.veleroCRDs)
	r.handleRoute("GET /assets/registry/ca.crt", r.registryCA)
	r.handleRoute("GET /assets/platform/ca.crt", r.platformCA)
	r.handleRoute("GET /ws/agent", r.agentWebSocket)
	if r.productInfo.Edition == "community" {
		r.handleRoute("POST /api/v1/community-migrations/authorizations", r.createCommunityMigrationAuthorization)
		r.handleRoute("GET /api/v1/community-migrations", r.listCommunityMigrations)
		r.handleRoute("POST /api/v1/community-migrations/source/sessions", r.openCommunityMigrationSession)
		r.handleRoute("GET /api/v1/community-migrations/source/{id}/inventory", r.communityMigrationInventory)
		r.handleRoute("POST /api/v1/community-migrations/source/{id}/freeze", r.freezeCommunityMigration)
		r.handleRoute("POST /api/v1/community-migrations/source/{id}/backup", r.backupCommunityMigration)
		r.handleRoute("GET /api/v1/community-migrations/source/{id}/manifest", r.communityMigrationManifest)
		r.handleRoute("GET /api/v1/community-migrations/source/{id}/export/{table}", r.communityMigrationExportBatch)
		r.handleRoute("GET /api/v1/community-migrations/source/{id}/credentials", r.communityMigrationCredentials)
		r.handleRoute("GET /api/v1/community-migrations/source/{id}/smtp", r.communityMigrationSMTP)
		r.handleRoute("POST /api/v1/community-migrations/source/{id}/handover", r.prepareCommunityMigrationHandover)
		r.handleRoute("POST /api/v1/community-migrations/source/{id}/commit", r.commitCommunityMigration)
		r.handleRoute("POST /api/v1/community-migrations/source/{id}/rollback", r.rollbackCommunityMigration)
	}
	if strings.TrimSpace(r.cfg.FrontendDir) != "" {
		r.handleRoute("GET /", r.frontend)
	}
}
