package httpserver

import "strings"

func (r *Router) routes() {
	r.mountPlatformRoutes()
	r.mountAuthRoutes()
	if r.productInfo.Edition == "community" {
		r.mux.HandleFunc("GET /api/v1/audit-logs", r.listAuditLogs)
	}
	if r.productInfo.Edition == "community" {
		r.mux.HandleFunc("GET /api/v1/diagnostic-logs", r.listDiagnosticLogs)
		r.mux.HandleFunc("GET /api/v1/diagnostic-logs/export", r.exportDiagnosticLogs)
		r.mux.HandleFunc("GET /api/v1/diagnostic-log-sources", r.diagnosticLogSources)
		r.mux.HandleFunc("POST /api/v1/support-bundles", r.createSupportBundle)
		r.mux.HandleFunc("GET /api/v1/support-bundles/{name}/download", r.downloadSupportBundle)
		r.mux.HandleFunc("DELETE /api/v1/support-bundles/{name}", r.deleteSupportBundle)
	}
	r.mux.HandleFunc("POST /api/v1/clusters/{id}/logs/collect", r.tenantGuard("cluster-log", r.collectClusterLogs))
	r.mux.HandleFunc("POST /api/v1/clusters/{id}/logs/search", r.tenantGuard("cluster-log", r.searchClusterLogs))
	if r.productInfo.Edition == "community" {
		r.mux.HandleFunc("GET /api/v1/users", r.listCommunityUsers)
		r.mux.HandleFunc("PATCH /api/v1/users/{id}", r.updateCommunityAdmin)
		r.mux.HandleFunc("POST /api/v1/users/{id}/password", r.resetCommunityAdminPassword)
		r.mux.HandleFunc("PATCH /api/v1/users/{id}/recovery-email", r.updateCommunityAdminRecoveryEmail)
	}
	r.mux.HandleFunc("GET /api/v1/email-settings", r.getEmailSettings)
	r.mux.HandleFunc("PUT /api/v1/email-settings", r.updateEmailSettings)
	r.mux.HandleFunc("POST /api/v1/email-settings/test", r.testEmailSettings)
	r.mux.HandleFunc("GET /api/v1/email-settings/configurations", r.listEmailSettings)
	r.mux.HandleFunc("POST /api/v1/email-settings/configurations", r.createEmailSettings)
	r.mux.HandleFunc("PUT /api/v1/email-settings/configurations/{id}", r.updateEmailSettingsByID)
	r.mux.HandleFunc("DELETE /api/v1/email-settings/configurations/{id}", r.deleteEmailSettings)
	r.mux.HandleFunc("POST /api/v1/email-settings/configurations/{id}/default", r.setDefaultEmailSettings)
	r.mux.HandleFunc("POST /api/v1/email-settings/configurations/{id}/test", r.testEmailSettingsByID)
	r.mux.HandleFunc("GET /api/v1/clusters", r.listClusters)
	r.mux.HandleFunc("POST /api/v1/cluster-registrations/cce/kubeconfigs", r.uploadCCEKubeconfig)
	r.mux.HandleFunc("POST /api/v1/cluster-registrations/cce/inspections", r.inspectCCEKubeconfig)
	r.mux.HandleFunc("POST /api/v1/cluster-registrations/cce/tasks", r.startCCEDirectRegistration)
	r.mux.HandleFunc("DELETE /api/v1/cluster-registrations/cce/kubeconfigs/{id}", r.deleteCCEKubeconfig)
	r.mux.HandleFunc("POST /api/v1/cluster-registrations/kubeconfigs", r.uploadCCEKubeconfig)
	r.mux.HandleFunc("POST /api/v1/cluster-registrations/inspections", r.inspectCCEKubeconfig)
	r.mux.HandleFunc("POST /api/v1/cluster-registrations/tasks", r.startCCEDirectRegistration)
	r.mux.HandleFunc("DELETE /api/v1/cluster-registrations/kubeconfigs/{id}", r.deleteCCEKubeconfig)
	r.mux.HandleFunc("PATCH /api/v1/clusters/{id}", r.tenantGuard("cluster", r.updateCluster))
	r.mux.HandleFunc("DELETE /api/v1/clusters/{id}", r.tenantGuard("cluster", r.deleteCluster))
	r.mux.HandleFunc("POST /api/v1/clusters/{id}/default", r.tenantGuard("cluster", r.setDefaultCluster))
	r.mux.HandleFunc("POST /api/v1/clusters/{id}/force-cleanup", r.tenantGuard("cluster", r.forceCleanupCluster))
	r.mux.HandleFunc("GET /api/v1/clusters/{id}/unregister/precheck", r.tenantGuard("cluster", r.precheckUnregisterCluster))
	r.mux.HandleFunc("POST /api/v1/clusters/{id}/unregister", r.tenantGuard("cluster", r.unregisterCluster))
	r.mux.HandleFunc("POST /api/v1/clusters/{id}/agent/upgrade", r.tenantGuard("cluster", r.upgradeClusterAgent))
	r.mux.HandleFunc("POST /api/v1/clusters/{id}/velero/upgrade", r.tenantGuard("cluster", r.upgradeClusterVelero))
	r.mux.HandleFunc("POST /api/v1/clusters/{id}/inventory/request", r.tenantGuard("cluster", r.requestClusterInventory))
	r.mux.HandleFunc("GET /api/v1/clusters/{id}/inventory/requests/{requestId}", r.tenantGuard("cluster", r.getClusterInventoryRequest))
	r.mux.HandleFunc("GET /api/v1/applications", r.listApplications)
	r.mux.HandleFunc("PATCH /api/v1/applications/{id}", r.tenantGuard("application", r.updateApplication))
	r.mux.HandleFunc("PUT /api/v1/applications/{id}/tags", r.tenantGuard("application", r.setApplicationTags))
	r.mux.HandleFunc("GET /api/v1/tags", r.listTags)
	r.mux.HandleFunc("POST /api/v1/tags", r.createTag)
	r.mux.HandleFunc("PATCH /api/v1/tags/{id}", r.tenantGuard("tag", r.updateTag))
	r.mux.HandleFunc("DELETE /api/v1/tags/{id}", r.tenantGuard("tag", r.deleteTag))
	r.mux.HandleFunc("GET /api/v1/storage-repositories", r.listStorageRepositories)
	r.mux.HandleFunc("POST /api/v1/storage-repositories", r.createStorageRepository)
	r.mux.HandleFunc("PATCH /api/v1/storage-repositories/{id}", r.tenantGuard("storage", r.updateStorageRepository))
	r.mux.HandleFunc("DELETE /api/v1/storage-repositories/{id}", r.tenantGuard("storage", r.deleteStorageRepository))
	r.mux.HandleFunc("POST /api/v1/storage-repositories/test", r.testStorageRepositoryDraft)
	r.mux.HandleFunc("POST /api/v1/storage-repositories/{id}/sync", r.tenantGuard("storage", r.syncStorageRepository))
	r.mux.HandleFunc("POST /api/v1/storage-repositories/{id}/test", r.tenantGuard("storage", r.testStorageRepository))
	r.mux.HandleFunc("GET /api/v1/policies", r.listPolicies)
	r.mux.HandleFunc("POST /api/v1/policies", r.createPolicy)
	r.mux.HandleFunc("PATCH /api/v1/policies/{id}", r.tenantGuard("policy", r.updatePolicy))
	r.mux.HandleFunc("DELETE /api/v1/policies/{id}", r.tenantGuard("policy", r.deletePolicy))
	r.mux.HandleFunc("GET /api/v1/protection-plans", r.listProtectionPlans)
	r.mux.HandleFunc("POST /api/v1/protection-plans", r.createProtectionPlan)
	r.mux.HandleFunc("POST /api/v1/protection-plans/{id}/activate", r.tenantGuard("plan", r.activateProtectionPlan))
	r.mux.HandleFunc("POST /api/v1/protection-plans/{id}/storage/reconfigure", r.tenantGuard("plan", r.reconfigureProtectionPlanStorage))
	r.mux.HandleFunc("DELETE /api/v1/protection-plans/{id}", r.tenantGuard("plan", r.deleteProtectionPlan))
	r.mux.HandleFunc("GET /api/v1/restore-points", r.listRestorePoints)
	r.mux.HandleFunc("GET /api/v1/restore-points/{id}/contents", r.getRestorePointContents)
	r.mux.HandleFunc("POST /api/v1/restore-points/delete", r.deleteRestorePoints)
	r.mux.HandleFunc("GET /api/v1/tasks", r.listTasks)
	r.mux.HandleFunc("GET /api/v1/protection-plans/{id}/latest-sync", r.latestPlanTask("backup"))
	r.mux.HandleFunc("GET /api/v1/protection-plans/{id}/latest-recovery", r.latestPlanRecoveryTask)
	r.mux.HandleFunc("GET /api/v1/tasks/{id}", r.getTask)
	r.mux.HandleFunc("GET /api/v1/tasks/{id}/events", r.tenantGuard("task", r.listTaskEvents))
	r.mux.HandleFunc("POST /api/v1/tasks/{id}/cancel", r.tenantGuard("task", r.cancelTask))
	r.mux.HandleFunc("POST /api/v1/tasks/{id}/retry", r.tenantGuard("task", r.retryRecoveryTask))
	r.mux.HandleFunc("POST /api/v1/tasks/{id}/cleanup-drill", r.tenantGuard("task", r.cleanupDrillTask))
	r.mux.HandleFunc("POST /api/v1/tasks/backup", r.createBackupTask)
	r.mux.HandleFunc("POST /api/v1/tasks/restore", r.createRestoreTask)
	r.mux.HandleFunc("POST /api/v1/tasks/drill", r.createDrillTask)
	r.mux.HandleFunc("POST /api/v1/tasks/takeover", r.createTakeoverTask)
	r.mux.HandleFunc("POST /api/v1/agent-tokens", r.createAgentToken)
	r.mux.HandleFunc("POST /api/v1/agent-tokens/validate", r.validateAgentToken)
	r.mux.HandleFunc("GET /prepare-node.sh", r.prepareNodeScript)
	r.mux.HandleFunc("GET /install.sh", r.installScript)
	r.mux.HandleFunc("GET /uninstall-agent.sh", r.agentUninstallScript)
	r.mux.HandleFunc("GET /disaster-handover.sh", r.disasterHandoverScript)
	r.mux.HandleFunc("POST /api/v1/disaster-handovers/validate", r.validateDisasterHandoverToken)
	r.mux.HandleFunc("GET "+veleroCRDsPath, r.veleroCRDs)
	// Keep the previous asset URL available while installed agents roll forward.
	r.mux.HandleFunc("GET /assets/velero/v1.17.1/crds.yaml", r.veleroCRDs)
	r.mux.HandleFunc("GET /assets/registry/ca.crt", r.registryCA)
	r.mux.HandleFunc("GET /assets/platform/ca.crt", r.platformCA)
	r.mux.HandleFunc("GET /ws/agent", r.agentWebSocket)
	if r.productInfo.Edition == "community" {
		r.mux.HandleFunc("POST /api/v1/community-migrations/authorizations", r.createCommunityMigrationAuthorization)
		r.mux.HandleFunc("GET /api/v1/community-migrations", r.listCommunityMigrations)
		r.mux.HandleFunc("POST /api/v1/community-migrations/source/sessions", r.openCommunityMigrationSession)
		r.mux.HandleFunc("GET /api/v1/community-migrations/source/{id}/inventory", r.communityMigrationInventory)
		r.mux.HandleFunc("POST /api/v1/community-migrations/source/{id}/freeze", r.freezeCommunityMigration)
		r.mux.HandleFunc("POST /api/v1/community-migrations/source/{id}/backup", r.backupCommunityMigration)
		r.mux.HandleFunc("GET /api/v1/community-migrations/source/{id}/manifest", r.communityMigrationManifest)
		r.mux.HandleFunc("GET /api/v1/community-migrations/source/{id}/export/{table}", r.communityMigrationExportBatch)
		r.mux.HandleFunc("GET /api/v1/community-migrations/source/{id}/credentials", r.communityMigrationCredentials)
		r.mux.HandleFunc("GET /api/v1/community-migrations/source/{id}/smtp", r.communityMigrationSMTP)
		r.mux.HandleFunc("POST /api/v1/community-migrations/source/{id}/handover", r.prepareCommunityMigrationHandover)
		r.mux.HandleFunc("POST /api/v1/community-migrations/source/{id}/commit", r.commitCommunityMigration)
		r.mux.HandleFunc("POST /api/v1/community-migrations/source/{id}/rollback", r.rollbackCommunityMigration)
	}
	if strings.TrimSpace(r.cfg.FrontendDir) != "" {
		r.mux.HandleFunc("GET /", r.frontend)
	}
}
